import type { User, Interest, Chat } from './types';
import { Film, Music, Plane, Utensils, Brush, Dumbbell, Code, Gamepad2, Camera, Mountain } from 'lucide-react';

export const interests: Interest[] = [
  { id: '1', name: 'Movies', icon: Film },
  { id: '2', name: 'Music', icon: Music },
  { id: '3', name: 'Travel', icon: Plane },
  { id: '4', name: 'Food', icon: Utensils },
  { id: '5',name: 'Art', icon: Brush },
  { id: '6', name: 'Fitness', icon: Dumbbell },
  { id: '7', name: 'Coding', icon: Code },
  { id: '8', name: 'Gaming', icon: Gamepad2 },
  { id: '9', name: 'Photography', icon: Camera },
  { id: '10', name: 'Hiking', icon: Mountain },
];

export const users: User[] = [
  {
    id: '1',
    name: 'Alex',
    age: 24,
    location: 'New York, NY',
    interests: ['1', '7', '8'],
    avatarUrl: 'https://picsum.photos/seed/user-1/400/400',
    avatarHint: 'smiling woman',
    isVerified: true,
    bio: "Tech enthusiast and gamer. Looking for friends to explore the city's food scene with.",
  },
  {
    id: '2',
    name: 'Ben',
    age: 28,
    location: 'San Francisco, CA',
    interests: ['2', '5', '9'],
    avatarUrl: 'https://picsum.photos/seed/user-2/400/400',
    avatarHint: 'man reading',
    isVerified: true,
    bio: 'Musician and artist who loves capturing moments. Let\'s go to a concert or a gallery.',
  },
  {
    id: '3',
    name: 'Chloe',
    age: 22,
    location: 'Austin, TX',
    interests: ['3', '6', '10'],
    avatarUrl: 'https://picsum.photos/seed/user-3/400/400',
    avatarHint: 'person hiking',
    isVerified: false,
    bio: 'Fitness lover and adventure seeker. Always down for a hike or a trip to somewhere new.',
  },
  {
    id: '4',
    name: 'David',
    age: 30,
    location: 'Chicago, IL',
    interests: ['1', '4', '7'],
    avatarUrl: 'https://picsum.photos/seed/user-4/400/400',
    avatarHint: 'woman painting',
    isVerified: true,
    bio: 'Software developer and movie buff. I believe the best conversations happen over a good meal.',
  },
  {
    id: '5',
    name: 'Emily',
    age: 26,
    location: 'Miami, FL',
    interests: ['2', '3', '6'],
    avatarUrl: 'https://picsum.photos/seed/user-5/400/400',
    avatarHint: 'man guitar',
    isVerified: true,
    bio: 'I love beach workouts and discovering new music. Looking for a travel buddy for my next adventure.',
  },
  {
    id: '6',
    name: 'Frank',
    age: 25,
    location: 'Los Angeles, CA',
    interests: ['1', '8', '9'],
    avatarUrl: 'https://picsum.photos/seed/user-6/400/400',
    avatarHint: 'person yoga',
    isVerified: false,
    bio: 'Film student and aspiring photographer. Let\'s shoot a short film or play some co-op games.',
  },
  {
    id: '7',
    name: 'Grace',
    age: 29,
    location: 'Seattle, WA',
    interests: ['4', '7', '10'],
    avatarUrl: 'https://picsum.photos/seed/user-7/400/400',
    avatarHint: 'bearded man',
    isVerified: true,
    bio: 'Coffee addict and backend developer. I spend my weekends hiking in the mountains.',
  },
  {
    id: '8',
    name: 'Henry',
    age: 23,
    location: 'Boston, MA',
    interests: ['5', '8', '2'],
    avatarUrl: 'https://picsum.photos/seed/user-8/400/400',
    avatarHint: 'woman camera',
    isVerified: true,
    bio: 'Art history major who loves indie music and retro games. Let\'s visit a museum or an arcade.',
  },
  {
    id: '9',
    name: 'Isabella',
    age: 27,
    location: 'Denver, CO',
    interests: ['3', '6', '10'],
    avatarUrl: 'https://picsum.photos/seed/user-9/400/400',
    avatarHint: 'person coding',
    isVerified: false,
    bio: 'Passionate about the great outdoors. Skiing in winter, hiking in summer. Join me!',
  },
  {
    id: '10',
    name: 'Jack',
    age: 31,
    location: 'Portland, OR',
    interests: ['1', '4', '9'],
    avatarUrl: 'https://picsum.photos/seed/user-10/400/400',
    avatarHint: 'chef cooking',
    isVerified: true,
    bio: 'Food blogger and photographer. I\'m on a quest to find the best food truck in Portland.',
  },
];

// Current user is user ID 0
export const currentUser: User = {
  id: '0',
  name: 'Taylor',
  age: 25,
  location: 'San Francisco, CA',
  interests: ['1', '7', '10'],
  avatarUrl: 'https://picsum.photos/seed/user-12/400/400',
  avatarHint: 'woman jogging',
  isVerified: true,
  bio: 'Just moved to SF! I love coding, watching indie films, and hiking. Looking for like-minded people to hang out with.',
};

export const chats: Chat[] = [
  {
    id: '1',
    userIds: ['0', '1'],
    messages: [
      { id: 'm1', senderId: '1', text: 'Hey! Saw we both like coding and movies. Have you seen the new Blade Runner?', timestamp: '2024-07-30T10:00:00Z' },
      { id: 'm2', senderId: '0', text: 'Hey Alex! Not yet, but it\'s on my list. I\'m a huge fan of sci-fi.', timestamp: '2024-07-30T10:01:00Z' },
      { id: 'm3', senderId: '1', text: 'Awesome! We should totally catch it sometime.', timestamp: '2024-07-30T10:02:00Z' },
    ],
  },
  {
    id: '2',
    userIds: ['0', '3'],
    messages: [
      { id: 'm4', senderId: '3', text: 'Hi! Your hiking pics look amazing. Any trail recommendations around SF?', timestamp: '2024-07-29T14:30:00Z' },
      { id: 'm5', senderId: '0', text: 'Hey Chloe! For sure, the Dipsea trail is incredible. We should go sometime!', timestamp: '2024-07-29T14:32:00Z' },
    ],
  },
  {
    id: '3',
    userIds: ['0', '4'],
    messages: [
        { id: 'm6', senderId: '4', text: 'Hey, another developer who likes movies! We\'re a rare breed haha.', timestamp: '2024-07-28T18:00:00Z' },
    ],
  },
];
